In [43]:
from bs4 import BeautifulSoup
import urllib.request as req
import pandas as pd

url = "https://www.rottentomatoes.com/top/bestofrt/?year=2019"
res = req.urlopen(url)

# HTML 분석
soup = BeautifulSoup(res, "html.parser")

topMovie2019 = soup.select("#top_movies_main > div > table a")
topMovie2019_Rating = soup.select("#top_movies_main > div > table span.tMeterScore")
topMovie2019_Reviews = soup.select("#top_movies_main > div > table td.hidden-xs")
  
topMovie2019Lists = [] # 영화제목
countLists = [] # 랭킹
Rating = [] # 예매율
Reviews = [] # 리뷰 갯수

count = 1
for movie100 in topMovie2019:
    #print(count, movie100.string.strip().replace("(2019)",""))
    countLists.append(count)
    topMovie2019Lists.append(movie100.string.strip().replace("(2019)",""))
    count += 1
    
for rate in topMovie2019_Rating:
    Rating.append(rate.string)

for review in topMovie2019_Reviews:
    Reviews.append(review.string)

In [17]:
# List 확인
print(countLists)
print(titleLists)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100]
['Parasite (Gisaengchung) ', 'Avengers: Endgame ', 'Knives Out ', 'Us ', 'Toy Story 4 ', 'The Irishman ', 'Little Women ', 'Booksmart ', 'The Farewell ', 'A Beautiful Day in the Neighborhood ', 'Marriage Story ', 'If Beale Street Could Talk ', 'Once Upon a Time In Hollywood ', 'Spider-Man: Far From Home ', 'Pain and Glory (Dolor y gloria) ', 'Shazam! ', 'Ford v Ferrari ', 'Dolemite Is My Name ', 'Apollo 11 ', 'The Lighthouse ', 'Rocketman ', 'Uncut Gems ', 'Amazing Grace ', 'They Shall Not Grow Old ', 'Ash Is Purest White ', 'Honeyland ', 'John Wick: Chapter 3 - Parabellum ', 'Honey Boy ', 'One Cut of the Dead (Kamera o tomeru na!) ', 'Fighting with My Family ', 'The Peanut Butter Falcon ', 'Knock Down the House ', 'Captain Marvel ', 'Birds of Passage (Pájaros de verano) ', 'Maiden ', 'Hustlers ', 'One Child Nation ', 'For Sama ', '3 Faces ', 'Chained for Life ', 'First Love (Hatsukoi) ', 'Woman at War (Kona fer í stríð) ', 'How to Train Your Dragon: The Hidden World ', 'White Riot ', 'Transit ', 'The Chambermaid (La camarista) ', 'Tigers Are Not Afraid (Vuelven) ', 'Midnight Traveler ', 'Stan & Ollie ', 'Ready or Not ', 'Atlantics ', 'Mickey and the Bear ', 'Deadwood: The Movie ', 'Varda by Agnès ', 'Scream, Queen! My Nightmare on Elm Street ', 'Hail Satan? ', 'Changing the Game ', 'The Heiresses (Las Herederas) ', 'Toni Morrison: The Pieces I Am ', 'The Last Black Man in San Francisco ', 'Midsommar ', 'The Mustang ', 'Wild Rose ', 'Blinded by the Light ', 'Bad Education ', 'Ad Astra ', '63 Up ', 'Homecoming: A Film by Beyoncé ', 'Too Late to Die Young (Tarde para morir joven) ', 'Gloria Bell ', 'By the Grace of God (Grâce à Dieu) ', 'Midnight Family ', 'Buñuel in the Labyrinth of the Turtles (Buñuel en el laberinto de las tortugas) ', 'Fiddler: A Miracle of Miracles ', 'American Factory ', 'Dirty God ', 'Making Waves: The Art of Cinematic Sound ', "I'm No Longer Here (Ya no estoy aquí) ", 'Working Woman ', 'The Cave ', 'The Kingmaker ', 'I Lost My Body ', 'Harpoon ', 'Love, Antosha ', 'Little Woods ', 'Jojo Rabbit ', 'Dark Waters ', 'The Amusement Park ', 'The Two Popes ', 'Mike Wallace Is Here ', 'Ray & Liz ', 'Be Natural: The Untold Story of Alice Guy-Blaché ', 'Monos ', 'Shadow ', 'Rojo ', 'In Fabric ', 'An Elephant Sitting Still (Da xiang xi di er zuo) ', 'It Must Be Heaven ', 'The Mortuary Collection ', 'Clemency ']

In [19]:
# countLists 만으로 DataFrame 생성
df = pd.DataFrame(data=countLists, columns=['Index'])
df['Titles'] = pd.Series(topMovie2019Lists)
df

    Index                                             Titles
0       1                           Parasite (Gisaengchung)
1       2                                 Avengers: Endgame
2       3                                        Knives Out
3       4                                                Us
4       5                                       Toy Story 4
..    ...                                                ...
95     96                                         In Fabric
96     97  An Elephant Sitting Still (Da xiang xi di er z...
97     98                                 It Must Be Heaven
98     99                           The Mortuary Collection
99    100                                          Clemency

[100 rows x 2 columns]

In [20]:
# csv로 저장
df.to_csv("./Data/topMovie2019Lists.csv", sep=",", encoding='utf-8', index=False)

In [46]:
# countLists, topMovie2019Lists, Rating, Reviews  으로 DataFrame 생성
df = pd.DataFrame(data=countLists, columns=['Rank'])
df['Rating'] = pd.Series(Rating)
df['Titles'] = pd.Series(topMovie2019Lists)
df['Reviews'] = pd.Series(Reviews)
df

    Rank Rating                                             Titles Reviews
0      1    98%                           Parasite (Gisaengchung)      459
1      2    94%                                 Avengers: Endgame      542
2      3    97%                                        Knives Out      464
3      4    93%                                                Us      551
4      5    97%                                       Toy Story 4      451
..   ...    ...                                                ...     ...
95    96    91%                                         In Fabric      160
96    97    96%  An Elephant Sitting Still (Da xiang xi di er z...      50
97    98    96%                                 It Must Be Heaven       49
98    99    95%                           The Mortuary Collection       66
99   100    91%                                          Clemency      150

[100 rows x 4 columns]

In [47]:
# csv로 저장
df.to_csv("./Data/topMovie2019Lists_final.csv", sep=",", encoding='utf-8', index=False)